### ISSUE TITLE
Add TeX Gyre fonts as the default serif, sans-serif, and monospace fonts

### ISSUE THREAD

**Issue by lukelbd** [lukelbd/proplot#104]
ProPlot makes some more widely-used (IMHO nicer) fonts the default rather than the DejaVu fonts. The new default font lists are:

```yaml
# ProPlot changes
font.serif: New Century Schoolbook, Century Schoolbook L, Utopia, ITC Bookman, Bookman, Nimbus Roman No9 L, Times New Roman, Times, Palatino, Charter, Computer Modern Roman, DejaVu Serif, Bitstream Vera Serif, serif
font.sans-serif: Helvetica, Arial, Lucida Grande, Verdana, Geneva, Lucid, Avant Garde, TeX Gyre Heros, DejaVu Sans, Bitstream Vera Sans, Computer Modern Sans Serif, sans-serif
font.monospace: Andale Mono, Nimbus Mono L, Courier New, Courier, Fixed, Terminal, Computer Modern Typewriter, DejaVu Sans Mono, Bitstream Vera Sans Mono, monospace
# Unchanged from matplotlib
font.cursive: Apple Chancery, Textile, Zapf Chancery, Sand, Script MT, Felipa, cursive
font.fantasy: Comic Sans MS, Chicago, Charcoal, ImpactWestern, Humor Sans, xkcd, fantasy
```

The DejaVu fonts packaged with matplotlib are pushed to the back. Unfortunately, this means the user experience will be inconsistent across systems, and I can't always rule out that a thin font will be picked up by matplotlib and used in place of the "regular" version (#94).

Luckily, it turns out TeX Gyre is a [whole font *series*](http://www.gust.org.pl/projects/e-foundry/tex-gy). It includes look-alikes for the Century fonts, Times new Roman, and the monospace Nimbus font. I have already added [TeX Gyre Heros](https://www.fontsquirrel.com/fonts/tex-gyre-heros), the Helvetica lookalike -- but I put it near the back because I didn't like that `'serif'` would be the only font category guaranteed to be the same on all systems.

So... I think it would be very straightforward to add the whole TeX Gyre series to ProPlot and put them at the front of the `font.serif`, `font.sans-serif`, and `font.monospace` lists! I will also convert the files from OTF to TTF before packaging, so PS files can be saved and PDFs can be saved without the backend embedding the entire font specification in the document (see matplotlib/matplotlib#1668).
